
# !include secrets.yaml




esphomeyaml:
  name: gragem
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: !secret wifiSSID
  password: !secret wifipass



mqtt:
  broker: !secret mqtttbrokerIP
  username: !secret mqttusername
  password: !secret mqttpassword




ota:
  password: !secret OTAgaragem



# Example configuration entry
sensor:
  - platform: ultrasonic
    trigger_pin: D1
    echo_pin: D2
    name: "Ultrasonic Sensor"
    # update_interval: 1s
    # timeout_meter: 2.5
    # timeouest_time: 2000us

logger:
  level: VERY_VERBOSE

web_server:
  port: 80