esphomeyaml:
  name: nuno
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: 'NJ'
  password: 'casadorex'

mqtt:
  broker: '192.168.1.158'
  username: 'nuno'
  password: 'braga'

# Enable logging
logger:

binary_sensor:
  - platform: gpio
    name: "Living Room Window"
    pin:
      number: 16
      inverted: True
      mode: INPUT_PULLUP

switch:
  - platform: gpio
    name: "Living Room Dehumidifer"
    pin: 5
ota:
  password: 'nuno'

i2c:
  # sda: D6
  scan: true

web_server:
  port: 80

# Example configuration entry
sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 15s