esphomeyaml:
  name: quarto
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: 'NJ'
  password: 'casadorex'

mqtt:
  broker: !secret mqtttbrokerIP
  username: !secret mqttusername
  password: !secret mqttpassword
# Enable logging
logger:

ota:
  password: !secret OTAquarto




# Example configuration entry
sensor:
  - platform: dht12
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 15s